version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      maven-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.junit.jupiter:junit-jupiter"
        versions: [">= 6.0.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
