name: Build

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: adopt
    - name: Build with Maven
      run: mvn -B clean verify --no-transfer-progress
